services:
  - type: web
    name: price-list-generator
    env: node
    region: oregon
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SCOPES
        value: read_products,write_products,read_orders,write_orders
      - key: SHOPIFY_APP_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: price-list-generator-db
          property: connectionString
    autoDeploy: false

  - type: pgsql
    name: price-list-generator-db
    region: oregon
    plan: starter
    databaseName: price_list_generator
    user: price_list_user
