services:
  - type: web
    name: price-list-generator
    runtime: node
    region: oregon
    plan: starter
    branch: main
    buildCommand: npm run render-build
    startCommand: npm run start:prod
    healthCheckPath: /health
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        value: 6b5a565d7969924d403aa57f66a1cfea
      - key: SHOPIFY_API_SECRET
        value: f86ea06f606d26c27fdc1897c602c0c8
      - key: SCOPES
        value: read_products,write_products,read_orders,write_orders
      - key: SHOPIFY_APP_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: price-list-generator-db
          property: connectionString

databases:
  - name: price-list-generator-db
    databaseName: price_list_generator
    user: price_list_user
    region: oregon
    plan: starter
